### ISSUE TITLE
ES6 import

### ISSUE THREAD

**Issue by hkjeffchan** [jaredwray/fumanchu#26]
Any chance to rewrite it to support es6 import syntax like the following?

import { handlebars, handlebarHelpers } from '@jaredwray/fumanchu';
handlebars.registerHelper(handlebarHelpers);

**Comment by hkjeffchan** [comment]
oh... i am stupid. You combined them together already.

This works:
import * as handlebars from '@jaredwray/fumanchu';

Any chance to make the following syntax works too?
import handlebars from '@jaredwray/fumanchu';

**Comment by jaredwray** [comment]
@hkjeffchan - thanks so much and I have done a couple of things with this pull request https://github.com/jaredwray/fumanchu/pull/29 and latest release.

Due to destructuring I believe the best case is to make it so you can do standard es6 without the `*` so right now it would look like this. 

```js
import handlebars from '@jaredwray/fumanchu';
```

if you want to access just the helpers then you would do it like this:
```js
import fumanchu from '@jaredwray/fumanchu';
cost {handlebarHelpers} = fumanchu;
```

With this you can get access to `handlebarHelpers` if you just want that. I have also added a small es6 test to validate this moving forward.
